function Precache(context)
    PrecacheModel("models/characters/combine_grunt/combine_grunt.vmdl", context)
    PrecacheModel("models/weapons/vr_alyxgun/vr_alyxgun.vmdl", context)
    PrecacheModel("models/weapons/vr_ipistol/vr_ipistol.vmdl", context)
    PrecacheModel("models/weapons/w_ipistol/ipistol_wm.vmdl", context)
    PrecacheModel("models/weapons/vr_shotgun/vr_flip_shotgun_body.vmdl", context)
    PrecacheResource("particle", "particles/weapon_fx/muzzleflash_pistol.vpcf", context)
    PrecacheResource("particle", "particles/weapon_fx/muzzleflash_player_rapidfire.vpcf", context)
    PrecacheResource("particle", "particles/weapon_fx/muzzleflash_smg_heavy.vpcf", context)
    PrecacheResource("particle", "particles/weapon_fx/muzzleflash_heavy_shotgun.vpcf", context)
end
