local p = Entities:GetLocalPlayer()
local z = Entities:FindByClassnameNearest("npc_zombie", p:GetOrigin(), 5000)
print("[AMP-D] TakeDamage=" .. type(z.TakeDamage) .. " NpcForceGoPosition=" .. type(z.NpcForceGoPosition) .. " GetPhysVelocity=" .. type(GetPhysVelocity))
local hp0 = z:GetHealth()
local info = CreateDamageInfo(p, p, Vector(0, 0, 0), z:GetCenter(), 10, 2)
local ok, err = pcall(function() z:TakeDamage(info) end)
DestroyDamageInfo(info)
print("[AMP-D] takedamage ok=" .. tostring(ok) .. " err=" .. tostring(err) .. " hp " .. hp0 .. " -> " .. z:GetHealth())
local target = z:GetOrigin() + Vector(80, 0, 0)
local ok2, err2 = pcall(function() z:NpcForceGoPosition(target, true) end)
print("[AMP-D] forcego ok=" .. tostring(ok2) .. " err=" .. tostring(err2))
local prop = Entities:FindByClassnameNearest("prop_physics", p:GetOrigin(), 800)
print("[AMP-D] prop vel " .. tostring(GetPhysVelocity(prop)) .. " ang " .. tostring(GetPhysAngularVelocity(prop)))
